server:
  port: 8082
spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://localhost:3306/subscription_db
    username: root
  kafka:
    bootstrap-servers: localhost:9092
