[supervisord]
nodaemon=true
user=root
logfile=/app/supervisord.log
pidfile=/var/run/supervisord.pid

[program:redis]
command=redis-server --protected-mode no --maxmemory 32mb --maxmemory-policy allkeys-lru
autostart=true
autorestart=true
stdout_logfile=/app/redis.log
stderr_logfile=/app/redis.err.log

[program:kafka]
# Extreme Low RAM Kafka: 96MB Heap, Serial GC
command=/opt/kafka/bin/kafka-server-start.sh /app/kafka-server.properties
autostart=true
autorestart=true
stdout_logfile=/app/kafka.log
stderr_logfile=/app/kafka.err.log
environment=KAFKA_HEAP_OPTS="-Xmx96M -Xms64M -XX:+UseSerialGC"

[program:spring-boot]
# Extreme Low RAM Spring: 224MB Heap, Serial GC, Small Stack
# We use 224MB to leave room for Native memory and Kafka
command=java -Xmx224M -Xms128M -Xss256k -XX:+UseSerialGC -Dserver.port=%(ENV_PORT)s -Dspring.profiles.active=prod -jar /app/app.jar
autostart=true
autorestart=true
stdout_logfile=/app/spring.log
stderr_logfile=/app/spring.err.log
priority=100
